name: Dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
      - run: yarn setup
      - run: yarn build appimage-x64
      - uses: actions/upload-artifact@v2
        with:
          name: 'AppImage'
          path: dist/*.AppImage
